#!/bin/bash

# The following environment vars must be set before the testing scripts
# can be run.
# (MGP == Magento Plugin)

export MGP_OS                      # OSX or Linux
export MGP_TEST_HOME               # Where you will run the tests, i.e.
                                   # /var/www/mgp or ~/Sites/mgp

#export MGP_
#export MGP_
#export MGP_
#export MGP_
#export MGP_


