<?php
if (Mage::helper('engage')->isEngageEnabled()):
?>
<script type="text/javascript">
    (function() {
        if( typeof window.janrain !== 'object')
            window.janrain = {};
        window.janrain.settings = {};

        janrain.settings.tokenUrl = "<?php echo Mage::getUrl('engage/rpx/token_url_add') ?>";  
        janrain.settings.appId = "<?php echo Mage::getStoreConfig('engage/vars/appid') ?>";
        janrain.settings.appUrl = "https://<?php echo Mage::getStoreConfig('engage/vars/realm') ?>";
        janrain.settings.type = 'modal';

        function isReady() {
            janrain.ready = true;
        };

        if(document.addEventListener) {
            document.addEventListener("DOMContentLoaded", isReady, false);
        } else {
            window.attachEvent('onload', isReady);
        }

        var e = document.createElement('script');
        e.type = 'text/javascript';
        e.id = 'janrainAuthWidget';

        if(document.location.protocol === 'https:') {
            e.src = 'https://rpxnow.com/js/lib/<?php echo Mage::helper('engage') -> rpxRealmName() ?>/engage.js';
        } else {
            e.src = 'http://widget-cdn.rpxnow.com/js/lib/<?php echo Mage::helper('engage') -> rpxRealmName() ?>/engage.js';
        }

        var s = document.getElementsByTagName('script')[0];
        s.parentNode.insertBefore(e, s);
    })();

</script>
<?php endif;?>
