<?php
if (Mage::helper('engage')->isEngageEnabled()):
    $source = (isset($_SERVER["HTTPS"]) && $_SERVER["HTTPS"] == "on") ? "https://" : "http://static.";
    $source .= "rpxnow.com/js/lib/rpx.js";
    ?>
    <script type="text/javascript" src="<?php echo $source; ?>"></script>
    <script type="text/javascript">
        RPXNOW.overlay = true;
        RPXNOW.language_preference = 'en';
    <?php
        if ($appId = Mage::getStoreConfig('engage/vars/appid')):
            $secure = Mage::app()->getStore()->isCurrentlySecure();
    ?>
              RPXNOW.init({appId: '<?php echo $appId; ?>',
                  xdReceiver: '<?php echo Mage::getUrl('engage/xdcomm', array('_nosid' => true, '_secure' => $secure)); ?>'});
    <?php endif; ?>
    </script>
<?php endif; ?>
