<script type="text/javascript">
(function() {
  if (typeof window.janrain !== 'object') window.janrain = {};
  if (typeof window.janrain.settings !== 'object') window.janrain.settings = {};
  if (typeof window.janrain.settings.share !== 'object') window.janrain.settings.share = {};
  if (typeof window.janrain.settings.packages !== 'object') janrain.settings.packages = ['share'];
  else janrain.settings.packages.push('share');

  janrain.settings.share.message = "<?php echo $this->message; ?>";

  function isReady() { janrain.ready = true; };
  if (document.addEventListener) {
    document.addEventListener("DOMContentLoaded", isReady, false);
  } else {
    window.attachEvent('onload', isReady);
  }

  var e = document.createElement('script');
  e.type = 'text/javascript';
  e.id = 'janrainWidgets';

  if (document.location.protocol === 'https:') {
    e.src = 'https://rpxnow.com/js/lib/<?php echo Mage::helper('engage')->rpxRealmName() ?>/widget.js';
  } else {
    e.src = 'http://widget-cdn.rpxnow.com/js/lib/<?php echo Mage::helper('engage')->rpxRealmName() ?>/widget.js';
  }

  var s = document.getElementsByTagName('script')[0];
  s.parentNode.insertBefore(e, s);
})();
function setShare(url, title, desc, img, provider)
{
	janrain.engage.share.setUrl(url);
	janrain.engage.share.setTitle(title);
	janrain.engage.share.setDescription(desc);
	janrain.engage.share.setImage(img);
	janrain.engage.share.showProvider(provider);
	janrain.engage.share.show();
}
</script>
