<?php
if (Mage::helper('engage')->isEngageEnabled()):
		//&& $this->getLayout()->getBlock('janrain_engage_scripts') != false):
?>
<link type="text/css" href="<?php echo Mage::helper('engage')->_baseSkin(); ?>/stylesheet.css" rel="stylesheet" />
<style type="text/css">
.rpx_icon_small {
background-image:url(<?php echo Mage::helper('engage')->_baseSkin(); ?>/providers_icons16.png);
}
.rpx_icon_large {
background-image:url(<?php echo Mage::helper('engage')->_baseSkin(); ?>/providers_icons32.png);
}
</style>
<?php endif; ?>