<div class="dashboard">
	<div class="box-account box-info">
		<div class="box-head">
			<h2>Janrain Engage Identifiers</h2>
		</div>
		<div class="col2-set">
			<div class="col-1">
				<div class="box">
					<div class="box-title">
						<h3>Current Providers</h3>
					</div>
					<div class="box-content">
						<ul>
						<?php
							$identifiers = Mage::helper('engage/identifiers')->get_identifiers(
								Mage::getSingleton('customer/session')->getCustomer()->getId()
							);

							foreach($identifiers as &$identifier) {
								echo '<li>' . $identifier->getIdentifier() . '</li>';
							}

						?>
						</ul>
					</div>
				</div>
			</div>
			<div class="col-2">
				<div class="box">
					<div class="box-title">
						<h3>Add New Provider</h3>
					</div>
					<div class="box-content">
						<?php
							$providers = Mage::helper('engage')->getRpxProviders();
							if (is_array($providers)) {
								$size = "large";
								$wrap_open = '<a class="rpxnow rpx_link_wrap" onclick="return false;" href="'
										. Mage::helper('engage')->getRpxAuthUrl()
										. '">';
								$wrap_close = '</a>';

								$rpx_buttons = '';
								foreach ($providers as $val) {
									$rpx_buttons .= '<div class="rpx_icon_' . $size . ' rpx_' . $val . '_' . $size . '" title="' . htmlentities($val) . '"></div>';
								}
								$buttons = '<div class="rpx_button"><div class="rpx_' . $size . '_icons">' . $rpx_buttons . '</div></div><div class="rpx_clear"></div>';

								echo $wrap_open . $buttons . $wrap_close;
							}
						?>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>