<?php
if (Mage::helper('engage/rpxcall')->isEngageEnabled()) {
    $page_title=$this->getLayout()->getBlock('head')->getTitle();
    $page_url=Mage::helper('core/url')->getCurrentUrl();
?>

<h2><a class="rpxnow" onclick="return false;"
href="https://bh-test01.rpxnow.com/openid/v2/signin?token_url=http%3A%2F%2F<?php echo $_SERVER['HTTP_HOST']; ?>%2Fjanrain-engage%2Frpx%2Ftoken_url%2F"> Sign In </a></h2>

<?php } ?>