<?php
if (Mage::helper('engage')->isEngageEnabled() && Mage::getStoreConfig('engage/vars/realm')):
$rpx_callback = Mage::getUrl() . "/janrain-engage/rpx/token_url";
$rpx_callback = urlencode($rpx_callback);
?>

<h2><a class="rpxnow" onclick="return false;"
href="<?php echo (Mage::getStoreConfig('engage/vars/realmscheme') == 'https') ? 'https' : 'http'; ?>://<?php echo Mage::getStoreConfig('engage/vars/realm'); ?>/openid/v2/signin?token_url=<?php echo $rpx_callback; ?>"> Sign In </a></h2>

<?php endif; ?>